default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: profport_train_alpha

development:
  <<: *default
  database: profport_train_alpha_dev

test:
  <<: *default
  database: profport_train_alpha_test

production:
  <<: *default
  database: profport_train_alpha_production